name: Build

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Checkout
        uses: actions/checkout@main
      - name: Build
        run: |
          echo "DATE=$(date +%Y%m%d)" >> $GITHUB_ENV
          docker build . > manjaro-rfs-${{ env.DATE }}.tar.xz
          ls
      - name: Release
        uses: softprops/action-gh-release@master
        with:
          name: Manjaro Docker ${{ env.DATE }}
          tag_name: ${{ env.DATE }}
          files: manjaro-rfs-${{ env.DATE }}.tar.xz
