name: Build

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Checkout
        uses: actions/checkout@main
      - name: Build
        run: |
          echo "DATE=$(date +%Y%m%d)" >> $GITHUB_ENV
          docker build --output manjaro-rfs-${{ env.DATE }}.tar.xz .
