name: Build

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Checkout
        uses: actions/checkout@main
      - name: Build
        run: |
          echo "DATE=$(date +%Y%m%d)" >> $GITHUB_ENV
          docker build --tag manjaro-rfs .
          docker save manjaro-rfs -o manjaro-rfs.tar
          gzip manjaro-rfs.tar
      - name: Release
        uses: softprops/action-gh-release@master
        with:
          name: Manjaro Docker ${{ env.DATE }}
          tag_name: ${{ env.DATE }}
          files: manjaro-rfs.tar.xz
